version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  app:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/doc_rails
    ports:
      - "3000:3000"
    depends_on:
      - db
  web:
    build:
      context: .
      dockerfile: Dockerfile_ngnix
    links:
      - app
    ports:
      - "80:80"
